### ISSUE TITLE
Upgrade to latest open release

### ISSUE THREAD

**Issue by cgillis-aras** [ArasLabs/server-side-file-check-in#1]
This needs to be tested against 11.0 SP9 and upgraded if necessary.

**Comment by EliJDonahue** [comment]
To-do: Update Visual Studio 2005 solution to VS 2013 or 2017. VS 2013 is preferable in case users have not yet upgraded to 2017. 

Or maybe add two new releases to the project- one with a VS 2013 solution and one with VS 2017.

**Comment by EliJDonahue** [comment]
Retarget to current open release: 11.0 SP12.

**Comment by sampoearas** [comment]
Project Archived.
