### ISSUE TITLE
May this also work for check-in Report from SSRS?

### ISSUE THREAD

**Issue by AngelaIp** [ArasLabs/server-side-file-check-in#2]
Hi,
What do you think about this:
Would this project also work as a basis for getting rendered SSRS reports (e.g. PDF) and store them as file in the Innovator vault?

Possible file paths would be:
```
http://<path to innovator>/Server/RSGateway.aspx
OR
http://<path to report server>/Reports/Pages/Report.aspx
```

**Comment by EliJDonahue** [comment]
It seems like you've answered your own question. :) Linking to your [add-ssrs-reports-to-vault](https://github.com/AngelaIp/add-ssrs-reports-to-vault) project.
